export default{
  data(){
    return{
      adviceList:["学雷锋活动","河南省","基层活动","阳光工程"],
      menu:[
          {
            name:"资讯",
            id:"a"
          },
          {
            name:"项目",
            id:"b"
          },
          {
            name:"团队",
            id:"c"
          },
        ],
      activeMenu:"a",
      resultList:[
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"3",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          endTime:10,
          realNum:100,
          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
        },
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"1",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          endTime:10,
          realNum:100,

          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
        },
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"2",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
          endTime:10,
          realNum:100,
        },
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"3",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          endTime:10,
          realNum:100,
          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
        },
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"1",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          endTime:10,
          realNum:100,
          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
        },
        {
          title:"河南省文化和旅游志愿者走进新疆",
          status:"4",
          to:"/",
          address:"安徽省黄山市歙县文化馆",
          timeStart:"2019.08.01",
          timeEnd:"2019.09.01",
          img:"static/images/villageStar/zhiyuan.jpg",
          endTime:10,
          realNum:100,
        }
      ],
      inputValue:"河南",
      seachValue:"河南",
      pageNum:1,//当前页码
      pageSize:20,
      total:20,
    }
  },
  methods:{
    search(){
      this.seachValue = this.inputValue;
    },
    changePage(){

    }
  }
}
